### ISSUE TITLE
Filepond instance returned doesn't have access to files due to proxying

### ISSUE THREAD

**Issue by thebleucheese** [johnnyasantoss/angularjs-filepond#1]
In the module you're setting the instance returned to a new object that has all the properties and methods of the actual filepond instance:

scope.onInit({ instance: proxy });

The problem with this is that it has no access to files used by the actual underlying instance (referenced by the var pond).  If you change the above to {instance: pond} getFiles() starts working along with all the other file functions for the instance.

I don't know the actual impact of this, nor do I totally understand why the object was partially cloned this way.  Can you shed some light on why that was done? Is there a workaround for using getFiles() or similar functions with the proxy - is it even needed?

My initial guess was the proxy might be necessary if there are more than one fileponds in an app where the module is loaded.  I haven't tested this out, I figured I'd ask here first.

**Comment by johnnyasantoss** [comment]
Hello!
Sorry for the delay to give you an answer about this.
I did this to follow the existing pattern on the other [angular package](https://github.com/pqina/ngx-filepond/blob/master/src/app/modules/filepond/filepond.component.ts#L33) :)

I think that it was done to prevent the end-user from accessing the DOM Manipulation methods, given that all the functionality still available through events that can be listened to using the [Filepond instance methods](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#event-methods) & [here](https://github.com/johnnyasantoss/angularjs-filepond/blob/master/tests/page/testApp.js#L37)
