### ISSUE TITLE
Cordova Support and Not Using Input for File

### ISSUE THREAD

**Issue by siddmegadeth** [johnnyasantoss/angularjs-filepond#2]
Cordova Support and Not Using Input for File
is there any way to pass file object directly from callback function to filepond inetead of using input tag

**Comment by johnnyasantoss** [comment]
Sorry for the delay. I didn't understand which input tag you are talking about, but if it helps, there is an example on how to use this API [here](https://github.com/johnnyasantoss/angularjs-filepond/blob/master/tests/page/testApp.js)
